with-expecter: true
dir: ./mocks
outpkg: mocks
mockname: "{{.InterfaceName}}"
packages:
  stoik.com/emailsec/internal:
    config:
        all: true
        recursive: true
        dir: ./mocks
        filename: "{{.InterfaceName}}.go"